const GAME_DATA = {
    locations: [
        { id: 0, name: "高陞店", type: "start", description: "起點：老殘在濟南住的客店。", price: 0, rent: 0 },
        { id: 1, name: "芙蓉街", type: "property", description: "濟南著名的老街，泉水與美食匯聚。", price: 120, rent: 25 },
        { id: 2, name: "油旋鋪", type: "property", description: "酥脆可口的油旋，濟南特色小吃。", price: 100, rent: 20 },
        { id: 3, name: "小布政司街", type: "property", description: "熱鬧的街道，老殘在此覓得客店。", price: 140, rent: 28 },
        { id: 4, name: "命運", type: "chance", description: "命運", price: 0, rent: 0 },
        { id: 5, name: "珍珠泉", type: "view", description: "泉水如串串珍珠上湧，庭院深深。", price: 180, rent: 35 },
        { id: 6, name: "曲水亭街", type: "property", description: "家家泉水，戶戶垂楊的代表老街。", price: 160, rent: 30 },
        { id: 7, name: "王府池子", type: "view", description: "濯纓泉，舊時王府院內清泉。", price: 170, rent: 32 },
        { id: 8, name: "鵲華橋", type: "property", description: "雇船的地方，通往歷下亭。", price: 150, rent: 30 },
        { id: 9, name: "甜沫鋪", type: "property", description: "鹹香適口的甜沫，最受歡迎的早餐。", price: 100, rent: 20 },
        { id: 10, name: "歷下亭", type: "property", description: "古亭，懸掛杜甫對聯。", price: 220, rent: 50, special: "歷下此亭古，濟南名士多" },
        { id: 11, name: "機會", type: "chance", description: "機會", price: 0, rent: 0 },
        { id: 12, name: "鐵公祠", type: "property", description: "紀念鐵鉉的祠堂。", price: 240, rent: 60, special: "四面荷花三面柳，一城山色半城湖" },
        { id: 13, name: "五龍潭", type: "property", description: "潭深莫測，傳說有秦瓊府邸。", price: 210, rent: 45 },
        { id: 14, name: "古玩店", type: "property", description: "雅致的店鋪，陳列著金石字畫。", price: 200, rent: 40 },
        { id: 15, name: "千佛山", type: "view", description: "遠眺千佛山，梵宇僧樓。", price: 200, rent: 40 },
        { id: 16, name: "黑虎泉", type: "view", description: "水聲喧騰，如虎嘯風生。", price: 210, rent: 45 },
        { id: 17, name: "趵突泉", type: "property", description: "天下第一泉，三窟突起，勢如鼎沸。", price: 350, rent: 90 },
        { id: 18, name: "古水仙祠", type: "property", description: "祠前有破匾，對聯雅致。", price: 180, rent: 35, special: "一盞寒泉薦秋菊，三更畫舫穿藕花" },
        { id: 19, name: "解放閣", type: "view", description: "登高望遠，俯瞰泉城新貌。", price: 230, rent: 50 },
        { id: 20, name: "大明湖", type: "property", description: "湖光山色，美不勝收。", price: 300, rent: 80 },
        { id: 21, name: "文廟", type: "view", description: "祭祀孔子之地，莊嚴肅穆。", price: 260, rent: 55 }
    ],
    questions: [
        { q: "「歷下此亭古，濟南名士多」這副對聯是誰寫的？", options: ["杜甫 (杜工部)", "何紹基", "鐵鉉", "刘鶚"], answer: 1, explanation: "上聯雖寫著'杜工部句'，但整副字實際是何紹基書寫的。" },
        { q: "鐵公祠祭祀的是明初哪位忠義之士？", options: ["于謙", "文天祥", "鐵鉉", "史可法"], answer: 2, explanation: "鐵公即是鐵鉉，明初兵部尚書，因抗擊燕王朱棣而死。" },
        { q: "文中形容大明湖的蘆葦在斜陽下好似什麼？", options: ["一塊無瑕碧玉", "一條粉紅絨毯", "一道金色光束", "一片皚皚白雪"], answer: 1, explanation: "文中寫道：'一片白花映著帶水氣的斜陽，好似一條粉紅絨毯'。" },
        { q: "「一盞寒泉薦秋菊，三更畫舫穿藕花」是在哪裡的對聯？", options: ["歷下亭", "鐵公祠", "古水仙祠", "趵突泉"], answer: 2, explanation: "這是古水仙祠前的舊對聯，意境優美。" },
        { q: "老殘在遊湖時聽到的聲音除了漁唱，還有什麼？", options: ["清脆鳥鳴", "隱隱雷聲", "船擦荷葉聲", "遠處琴聲"], answer: 2, explanation: "文中描寫細膩：'那荷葉初枯，擦的船嗤嗤價響'。" },
        { q: "「四面荷花三面柳」的下聯是？", options: ["一城山色半城湖", "家家泉水戶戶垂楊", "三更畫舫穿藕花", "半城山色一城湖"], answer: 0, explanation: "這是鐵公祠的著名對聯，概括了濟南的風光。" },
        { q: "老殘遊記的作者是誰？", options: ["劉鶚", "蒲松齡", "魯迅", "吳敬梓"], answer: 0, explanation: "老殘遊記為清末劉鶚(字鐵雲)所著。" },
        { q: "文中描述千佛山的倒影在湖中顯得如何？", options: ["波光粼粼", "極其清楚", "若隱若現", "模糊不清"], answer: 1, explanation: "文中寫道：'彷彿有一張水墨畫卷...極其清楚'。" },
        { q: "老殘到達濟南府時，覺得這裡的人家怎麼樣？", options: ["大多貧困", "家家泉水，戶戶垂楊", "喧鬧繁華", "古樸破舊"], answer: 1, explanation: "這是老殘對濟南城的經典印象。" },
        { q: "文中提到「梵宇僧樓」是指哪裡的建築？", options: ["歷下亭周圍", "千佛山上", "鐵公祠內", "大明湖畔"], answer: 1, explanation: "這是形容遠眺千佛山時看到的寺廟建築群。" },
        { q: "老殘僱的是什麼船遊湖？", options: ["豪華畫舫", "小舢板", "烏篷船", "竹筏"], answer: 1, explanation: "老殘喜愛安靜，僱了一隻沒人坐的小舢板。" },
        { q: "文中描述哪種花正在盛開或剛過花期？", options: ["荷花", "菊花", "梅花", "桃花"], answer: 0, explanation: "文中是秋季，但仍有殘荷，且多次描寫荷花(蓮花)景色。" },
        { q: "老殘在濟南聽到的著名曲藝形式是什麼？", options: ["京劇", "梨花大鼓", "山東快書", "河南墜子"], answer: 1, explanation: "老殘在明湖居聽白妞說書，即是梨花大鼓（山東大鼓）。" },
        { q: "白妞說書的高超技藝中，文中用了哪個比喻形容聲音的高亢？", options: ["如黃鶯出谷", "如一線鋼絲拋入天際", "如萬馬奔騰", "如珠落玉盤"], answer: 1, explanation: "文中形容聲音'像一線鋼絲拋入天際'，極具畫面感。" },
        { q: "「家家泉水，戶戶垂楊」形容的是哪座城市？", options: ["蘇州", "杭州", "濟南", "揚州"], answer: 2, explanation: "這是對濟南老城風貌的經典描寫。" },
        { q: "老殘遊記的主角老殘，他的職業是什麼？", options: ["當鋪老闆", "搖串鈴的郎中", "朝廷官員", "教書先生"], answer: 1, explanation: "老殘是一個走江湖行醫的郎中。" },
        { q: "《老殘遊記》被譽為清末四大什麼小說之一？", options: ["譴責小說", "言情小說", "武俠小說", "神魔小說"], answer: 0, explanation: "它與《官場現形記》、《二十年目睹之怪現狀》、《孽海花》並稱晚清四大譴責小說。" },
        { q: "文中提到千佛山上的「梵宇僧樓」與什麼顏色相映？", options: ["翠綠的松柏", "蒼松翠柏與丹紅霞氣", "金黃的銀杏", "潔白的雲朵"], answer: 1, explanation: "文中描寫：'蒼松翠柏，高下相間'且映著'丹紅的霞氣'。" },
        { q: "老殘在遊覽大明湖時，季節是？", options: ["春暖花開", "炎炎夏日", "秋高氣爽", "寒冬臘月"], answer: 2, explanation: "從'秋蓉老圃'、'荷葉初枯'等描寫可以知道是秋天。" },
        { q: "古水仙祠供奉的是誰？", options: ["大禹", "媽祖", "張大仙", "並未明確提及但多指水神"], answer: 3, explanation: "書中並未詳細考證神祇，重點在於祠前的風景與對聯。" },
        { q: "下列哪一個不是大明湖的景色？", options: ["歷下亭", "鐵公祠", "雷峰塔", "千佛山倒影"], answer: 2, explanation: "雷峰塔位於杭州西湖。" },
        { q: "「三更畫舫穿藕花」中的「三更」意指什麼時候？", options: ["清晨", "正午", "半夜", "黃昏"], answer: 2, explanation: "三更通常指半夜十一點到一點，形容夜遊的情趣。" },
        { q: "老殘在哪裡看到了「佛山倒影」的奇景？", options: ["鐵公祠後的敞軒內", "歷下亭中", "鵲華橋上", "高陞店門口"], answer: 0, explanation: "老殘到了鐵公祠，在後面的敞軒剛坐下，便看到了千佛山倒影。" },
        { q: "作者描寫王小玉說書聲音「忽又變出無限聲音」時，用了什麼比喻？", options: ["花塢春曉，百鳥亂鳴", "大珠小珠落玉盤", "鐵騎突出刀槍鳴", "餘音繞樑，三日不絕"], answer: 0, explanation: "文中雲：'忽又變出無限聲音... 像那花塢春曉，百鳥亂鳴一般'。" }
    ],
    chanceCards: [
        { text: "在路邊攤吃了美味的油旋，精神百倍！", effect: "money", value: 50 },
        { text: "船被厚厚的荷葉夾住，動彈不得。", effect: "skip_turn", value: 1 },
        { text: "欣賞千佛山在湖中的倒影，心情大好。", effect: "money", value: 30 },
        { text: "在芙蓉街偶遇濟南名士，相談甚歡。", effect: "money", value: 100 },
        { text: "歷下亭油漆剝蝕，捐款修繕亭子。", effect: "money", value: -40 },
        { text: "被驚起的水鳥嚇了一跳，掉了一個銅板。", effect: "money", value: -20 },
        { text: "品嚐了甜沫，暖胃又暖心。", effect: "money", value: 40 },
        { text: "在小布政司街買了一些土產。", effect: "money", value: -30 }
    ],
    destinyCards: [
        { text: "秋山紅葉，景色宜人，獲得一次擲骰機會。", effect: "roll_again", value: 0 },
        { text: "客店客滿，只好多付房錢。", effect: "money", value: -50 },
        { text: "在古玩店發現古人墨寶，價值連城！", effect: "money", value: 300 },
        { text: "天色已晚，回高陞店休息。", effect: "teleport", value: 0 },
        { text: "參觀文廟，獲得智慧啟發。", effect: "money", value: 80 },
        { text: "突然下起大雨，在古水仙祠躲雨。", effect: "stop", value: 1 }
    ]
};
